# Generated by Django 5.0.6 on 2024-06-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_customer_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="preaprroved_at",
            new_name="preapproved_at",
        ),
    ]
