# Generated by Django 5.0.6 on 2024-06-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="outstanding",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="taken_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
