# Generated by Django 5.0.6 on 2024-06-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_alter_loan_taken_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="outstanding",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
